### ISSUE TITLE
GDI+ nearest neighbour interpolation

### ISSUE THREAD

**Issue by nakst** [nakst/imgview#2]
The first column and row are cut off by half a pixel because of GDI+'s nearest neighbour interpolation. This also breaks the "Color under mouse" display.

**Comment by Zero3K** [comment]
1. I do not see any issues with images that I view with ImgView.
2. The "Color under mouse" is showing properly for me.

I am running it under Windows 7 SP1 x64.

**Comment by nakst** [comment]
Example of incorrect behaviour: https://i.imgur.com/cT8ZpMu.png

**Comment by nakst** [comment]
Fixed in 74648b4.
