### ISSUE TITLE
Errors when compiling it using Visual Studio 2019

### ISSUE THREAD

**Issue by Zero3K** [nakst/imgview#5]
I am getting the following errors when compiling it using Visual Studio 2019 via the build.bat:

imgview.cpp
c1xx: fatal error C1083: Cannot open source file: '..\imgview.cpp': No such file
 or directory

After fixing the buiild.bat:

imgview.cpp
imgview.cpp(810): error C2664: 'HANDLE CreateThread(LPSECURITY_ATTRIBUTES,SIZE_T
,LPTHREAD_START_ROUTINE,LPVOID,DWORD,LPDWORD)': cannot convert argument 3 from '
DWORD (__cdecl *)(void *)' to 'LPTHREAD_START_ROUTINE'
imgview.cpp(810): note: None of the functions with this name in scope match the
target type
C:\Program Files\Windows Kits\10\include\10.0.19041.0\um\processthreadsapi.h(170
): note: see declaration of 'CreateThread'

**Comment by nakst** [comment]
Are you trying to compile for 32 bit mode? I think that's what might cause this issue.

**Comment by Zero3K** [comment]
Yes. I am trying to compile a 32-bit build of it.

**Comment by Yakvi** [comment]
I have created #8 to fix this bug. As of the second second part, if compiling under 32-bit mode, adding `WINAPI` on line 673 fixes the compiler error: 

673 `DWORD WINAPI GetFolderContents(void *_filePath) {`

However, doing so exposes a linker error `unresolved external symbol __ftol2_sse`. As by the guide [here](https://hero.handmade.network/forums/code-discussion/t/94-guide_-_how_to_avoid_c_c++_runtime_on_windows), you can use the following snippet to define `_ftol2_sse`: 
    #ifdef __cplusplus 
    extern "C"
    #endif
    __declspec(naked) void _ftol2_sse()
    {
        __asm
        {
            fistp dword ptr [esp-4]
            mov   eax,[esp-4]
            ret
        }
    }
