### ISSUE TITLE
Issue with minimizing and restoring its window

### ISSUE THREAD

**Issue by Zero3K** [nakst/imgview#6]
When I minimize and restore its window, the image is missing, there's some symbols in the Mouse coordinates, there's some symbols in the Anchor offset and the Color under mouse is all zeroes.

**Comment by nakst** [comment]
What version of Windows are you using, and what theme settings are active?

**Comment by Zero3K** [comment]
1. Windows 7 x64.
2. Classic Theme

**Comment by nakst** [comment]
I'm not able to reproduce this bug. Could you please upload a video of it occurring, including the message log in Spy++ of the "frame" window and the "viewport" window.

**Comment by Zero3K** [comment]
I think it happens with large images.

**Comment by nakst** [comment]
I think bb99ba8 will fix this. Let me know if you still have issues.
